store_homepage:
    path:     /
    defaults: { _controller: StoreBundle:Default:index }

store_ann:
    resource: "@StoreBundle/Controller/"
    type:     annotation

storia:
    path:     /storia
    defaults: { _controller: StoreBundle:Storia:index }